Sistema3SS_2020/Sistema3SS_2020/Models/Proyeccione.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema3SS_2020.Models
{
    public partial class Proyeccione
    {
        public int Id { get; set; }
        public int IdPresupuesto { get; set; }
        public DateTime? FinalSemana { get; set; }
        public DateTime? IncioSemana { get; set; }
        public double? GastoEstimado { get; set; }
        public int? IdSemana { get; set; }
    }
}

Sistema3SS_2020/Sistema3SS_2020/Controllers/AdminProyectosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sistema3SS_2020.Models;

namespace Sistema3SS_2020.Controllers
{
    public class AdminProyectosController : Controller
    {
        private Sistema3SSPruebasContext _context;

        public AdminProyectosController(Sistema3SSPruebasContext context)
        {
            this._context = context;
        }

        static int idProyecto;
        Presupuesto presupuesto = new Presupuesto();
        Proyecto proyecto = new Proyecto();
        Granja granja = new Granja();

        public ActionResult CrearProyecto()
        {
            try
            {
                Proyecto proyecto = new Proyecto();
                
                return View(proyecto);
            }
            catch (Exception e)
            {
                var a = e.Message;
                throw;
            }
        }
        public ActionResult Index()
        {
            var granjas = _context.Granjas.ToList();
            ViewData["Granjas"] = new SelectList(granjas, "Id", "Nombre");

            ViewBag.Temporadas = _context.Temporadas.ToList();
            ViewBag.Proyectos = _context.Proyectos.Include(y => y.IdUsuarioNavigation).ToList().OrderBy(x => x.FechaInicial);

            return View();
        }

        
        [HttpPost]
        public void CrearProyecto(CreateProyecto proyecto)
        {
            try
            {
                Proyecto p = new Proyecto()
                {
                    FechaInicial = proyecto.FechaInicial,
                    FechaFinal = proyecto.FechaFinal,
                    IdUsuario = 3
                };
                
                _context.Proyectos.Add(p);
                _context.SaveChanges();

                DetalleProyecto dp = new DetalleProyecto()
                {
                    IdProyecto = p.Id,
                    IdTemporada = proyecto.IdTemporada
                };

                _context.DetalleProyectos.Add(dp);
                _context.SaveChanges();

            }
            catch (Exception e)
            {
                var a = e.Message;
                throw;
            }
        }

        public class CreateProyecto {
            public DateTime FechaInicial { get; set; }
            public DateTime FechaFinal { get; set; }
            public int IdGranja { get; set; }
            public int IdTemporada { get; set; }
        }

    }
}

Sistema3SS_2020/Sistema3SS_2020/Views/AdminProyectos/CrearPresupuesto.cshtml
@model Sistema3SS_2020.Models.Proyecto
<html lang="en">
<head>
</head>
<body class="bg-light">
    <partial name="/Views/Shared/NavBar.cshtml" />
    <!-- Modal -->
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Agregar <b>Presupuesto a proyecto</b></h2>
                        </div>
                        <div class="col-sm-6">
                            <a class="btn btn-danger" data-toggle="tooltip" title="Regresar a lista de proyectos" href="@Url.Action("Index","AdminProyectos")"><i class="material-icons">&#xe408;</i> <span>Atras</span></a>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                    </thead>
                    <tbody>
                        <form method="post" action="@Url.Action("CrearPresupuesto","AdminProyectos")">
                            <div class="container">
                                <div class="row mb-4">
                                    <div class="col-4 mb-4">
                                        <div class="col-10 mb-0">
                                            <label for="country">Presupuesto</label>
                                            <select onchange="SecuenciaDeCambios();" class="custom-select d-block w-100" id="TipoPres" name="TipoPres" required="">
                                                <option value="0">Tipo...</option>
                                                
                                            </select>
                                            <div class="invalid-feedback">
                                                Por favor de selccionar un elemnto valido
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4 ">
                                        <div class="col-10 mb-0">
                                            <label for="state">Granja</label>
                                            <select disabled onchange="jsFuncionNumeroEstanques();" name="SelectGranja" class="custom-select d-block w-100" id="SelectGranja" runat="server">
                                                <option value="0">Nombre...</option>
                                                
                                            </select>
                                            <div class="invalid-feedback">
                                                Por favor de selccionar un elemnto valido
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4 ">
                                        <div class="col-10 mb-0">
                                            <label for="state">Concepción</label>
                                            <select disabled onchange="jsFuncionNumeroEstanques();" name="SelectConcepcion" class="custom-select d-block w-100" id="SelectConcepcion">
                                                <option value="0">Selecionar...</option>
                                                
                                            </select>
                                            <div class="invalid-feedback">
                                                Por favor de selccionar un elemnto valido
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="col-10 mb-0" id="Est1">
                                            <label for="state">Selecion estanque</label>
                                            <select disabled name="Selectestanquest" class="custom-select d-block w-100" id="Selectestanquest">
                                                <option value="">Numero...</option>
                                            </select>
                                            <div class="invalid-feedback">
                                                Por favor de selccionar un elemnto valido
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="col-10 mb-0">
                                            <label for="country">Gasto</label>
                                            <select class="custom-select d-block w-100" name="SelectGasto" id="SelectGasto" required="">
                                                <option value="">Nombre...</option>
                                               
                                            </select>
                                            <div class="invalid-feedback">
                                                Por favor de selccionar un elemnto valido
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="col-10 mb-0">
                                            <label for="country">Concepto</label>
                                            <select class="custom-select d-block w-100" name="SelectConcepto" id="SelectConcepto" required="">
                                                <option value="">contenido...</option>
                                                
                                            </select>
                                            <div class="invalid-feedback">
                                                Por favor de selccionar un elemnto valido
                                            </div>
                                        </div>
                                    </div>
                                    <br />
                                    <br />
                                    <!-- Small modal -->
                                    <div class="col-4 m-2">
                                        <button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target=".bd-example-modal-sm"> <a href="#" role="button" class="btn btn-secondary popover-test" title="Solo para la Concepcíon 'Multiestanque'" data-content="Solo para la Concepcíon 'Multiestanque'">Estanques</a></button>
                                    </div>
                                    <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-sm">
                                            <div class="modal-content">
                                                <div class="col-4">
                                                    <div class="col-10 mb-0" id="Est1">
                                                        <div class="col-10 mb-0" id="Est2">
                                                            <div class="container" id="checkboxes">

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Small modal /-->
                                </div>
                                <br />
                                <br />
                                <button type="submit" class="btn btn-primary">Crear Presupuesto</button>
                            </div>
                        </form>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>
</html>

Sistema3SS_2020/Sistema3SS_2020/Views/AdminProyectos/CrearProyecto.cshtml
@model Sistema3SS_2020.Models.Proyecto
<html>
<head>
    <script src="~/Scrips/Proyecto.js"></script>
</head>
<body>
    <partial name="/Views/Shared/NavBar.cshtml" />
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-6">
                            <h2>Crear <b>Proyecto</b></h2>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                    </thead>
                    <tbody>
                        <div class="flex-row">
                            <div class="col-md-10">
                                <form >
                                    <div class="active col-md-3">
                                        @*<label hidden asp-for="id" class="control-label"></label>
                                        <input hidden asp-for="id" class="form-control" />
                                        <span asp-validation-for="id" class="text-danger"></span>*@
                                    </div>
                                    <div class="active col-md-5">
                                        @*<label class="control-label"> Fecha de inicio</label>
                                        <input asp-for="fecha_incial" class="form-control" />
                                        <span asp-validation-for="fecha_incial" class="text-danger"></span>*@
                                    </div>
                                    <div class="col-md-5">
                                        @*<label class="control-label"> Fecha de culminación</label>
                                        <input asp-for="fecha_final" class="form-control" />
                                        <span asp-validation-for="fecha_final" class="text-danger"></span>*@
                                    </div>
                                    <div class="col-md-7">
                                        @*<label hidden asp-for="idUsuarioAutoriso" class="control-label"></label>
                                        <input hidden asp-for="idUsuarioAutoriso" class="form-control" />
                                        <span asp-validation-for="idUsuarioAutoriso" class="text-danger"></span>*@
                                    </div>
                                    <div class="col-md-7">
                                        <label class="control-label">Granjas</label>
                                        <select onchange="AgregarGranja();" name="SelectGranja" class="custom-select d-block w-100" id="SelectGranja" runat="server">
                                            <option value="0">Nombre...</option>
                                            
                                        </select>
                                        <div>
                                            <label name="ejempo1" class="form-control" runat="server">Granjas añadidas</label>
                                            <div id="DivSelectGranja" class="container">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label"> Temporada</label>
                                        <select name="SelectTempo" class="custom-select d-block w-100" id="SelectTempo" runat="server">
                                            <option value="0">Nombre...</option>
                                            
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="CREAR PROYECTO" class="form-control" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

Sistema3SS_2020/Sistema3SS_2020/Views/AdminProyectos/Index.cshtml
@model IEnumerable<Sistema3SS_2020.Models.Proyecto>

<partial name="/Views/Shared/NavBar.cshtml" />

<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Administrar <b>Proyectos</b></h2>
                    </div>
                    <div class="col-sm-6">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                            Agregar Proyecto
                        </button>

                    </div>
                </div>
            </div>
            <br />

            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th>Fecha de inicio de proyecto</th>
                        <th>Fecha de termino de proyecto</th>
                        <th>Autorizó</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var proy in ViewBag.Proyectos)
                    {
                    <tr>
                        <td></td>
                        <td>@proy.FechaInicial.ToString("dd MMM yyyy")</td>
                        <td>@proy.FechaFinal.ToString("dd MMM yyyy")</td>
                        <td>@proy.IdUsuarioNavigation.Nombre @proy.IdUsuarioNavigation.ApellidoPaterno @proy.IdUsuarioNavigation.ApellidoMaterno</td>
                        <td><i class="fas fa-address-book"></i> <i class="fas fa-address-book"></i></td>

                    </tr>
                    }
                </tbody>
            </table>
            
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar Proyecto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Fecha Inicio</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" id="FechaInicial">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Fecha Final</label>
                        <div class="col-sm-10">
                            <input type="date" class="form-control" id="FechaFinal">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Granjas</label>
                        <div class="col-sm-10">
                            <select class="form-control" asp-items="ViewBag.Granjas" id="IdGranja" required></select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Temporadas</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="IdTemporada" required>
                                @foreach (var item in ViewBag.Temporadas)
                                {
                                    <option value="@item.Id"> @item.FechaInicial.ToString("dd MMM yyyy") - @item.FechaFinal.ToString("dd MMM yyyy") </option>

                                }
                            </select>
                        </div>
                    </div>

                    <div class="float-right">
                        <button data-dismiss="modal" class="btn btn-danger">Cancelar</button>
                        <button onclick="AddProyecto()" class="btn btn-success">Agregar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
   

    function AddProyecto() {
        event.preventDefault();
        var CreateProyecto = {
            FechaInicial : $("#FechaInicial").val(),
            FechaFinal : $("#FechaFinal").val(),
            IdGranja : $("#IdGranja").val(),
            IdTemporada : $("#IdTemporada").val(),
        }

        console.log(CreateProyecto)

        $.ajax({
            type: 'POST',
            url: "AdminProyectos/CrearProyecto",
            data: CreateProyecto,
            success: function (data, textStatus, jqXHR) {
                location.reload();
            },
            error: function (e) { }
        });
    }

</script>

Sistema3SS_2020/Sistema3SS_2020/Views/AdminProyectos/Proyecciones.cshtml
<html>
<head>
</head>

<body>
    <partial name="/Views/Shared/NavBar.cshtml" />
    <form method="post">
        <div class="container">
            <label>Semanas</label>
            <select>
                <option>
                </option>
            </select>
            <label><spam class="alert-dark">$</spam> </label>
            <input class="text-body" placeholder="Agregar cantidad..." title="Agregar cantidad estimada" />
        </div>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">SEMANA</th>
                    <th scope="col">Cantidad proyectada</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                </tr>
                <tr>
                    <th scope="row">2</th>
                </tr>
                <tr>
                    <th scope="row">3</th>
                </tr>
                <tr>
                    <th>Total $0 </th>
                </tr>
            </tbody>
        </table>
    </form>
</body>
</html>